"""DB migration

Revision ID: 45b19e853308
Revises: 4bdd014eabee
Create Date: 2022-01-16 02:26:46.049355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45b19e853308'
down_revision = '4bdd014eabee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
