"""Adding created at and updated to db models

Revision ID: 61ceebc1a2eb
Revises: 48fad9e7af82
Create Date: 2022-01-16 13:53:28.585103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61ceebc1a2eb'
down_revision = '48fad9e7af82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_account', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('oauth_account', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('user', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_column('oauth_account', 'updated_at')
    op.drop_column('oauth_account', 'created_at')
    # ### end Alembic commands ###
