"""DB migration

Revision ID: be280c9093d8
Revises: 48fad9e7af82
Create Date: 2022-04-15 22:21:50.179522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be280c9093d8'
down_revision = '48fad9e7af82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('scopes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'scopes')
    # ### end Alembic commands ###
